### ISSUE TITLE
Resolve "Add existing version of automated metadata extraction" - [merged]

### ISSUE THREAD

**Issue by sferenz** [NFDI4Energy/SMECS#67]
In GitLab by @Aidajafarbigloo on Feb 10, 2023, 02:12

_Merges 3-add-existing-version-of-automated-metadata-extraction -> master_

Closes #3 
Working on extracting metadata from project URL.

**Description:**

**Features**
- Metadata of a GitLab project can be extracted via "Project URL" and "Personal Token Key".
- Tooltip, added to the initial form, gives more information to the user about the "Personal Token Key".
- The entered URL is displayed at the top of the form that shows the extracted metadata.
- Metadata is being shown in the format of a form including labels as keys and inputs as values.
- Data in the form can be edited.
- Extracted "Programming Languages" are displayed in a single input field, separated by commas.
- Number of "Contributors" can be calculated and shown dynamically after extraction.
- Metadata is being shown in a textarea in the JSON format.
- There is a possibility of seeing the changed data simultaneously in the textarea.
- Main JSON data or edited version can be downloaded via a download button.
- Style of the software becomes more structured.

**Needs to be solved** 
- "Contributors" and "Authors" cannot be edited via the form.

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Feb 10, 2023, 02:12

requested review from @sferenz

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Feb 10, 2023, 12:19

added 1 commit

<ul><li>2c88597e - Initial update of index, form creation for metadata extraction (URL&amp; Token)</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=600638098&start_sha=c0f220ce0a2fc16a260af81b60aa8b683c8e052d)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Feb 10, 2023, 12:27

added 1 commit

<ul><li>f61c3db4 - Added new html file for showing extracted data based on entered URL &amp; Token</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=600646680&start_sha=2c88597e09187ca3abadc84fc153d91ce369c97f)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Feb 10, 2023, 13:21

added 1 commit

<ul><li>2a6a74cb - Extracting &amp; showing extracted metadata based on URL &amp; Token (V 1.0)</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=600704285&start_sha=f61c3db4913c3d060acf878dfe0776d7f808efc4)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Feb 10, 2023, 13:28

added 1 commit

<ul><li>3fea66df - Added new path for showing extracted data in showdata.html</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=600711334&start_sha=2a6a74cbbbf362cbf187e17b7a626eac5aa3d560)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Feb 14, 2023, 00:32

added 1 commit

<ul><li>c647923f - Cleaning up &quot;Views.py&quot; from metadata extracting functions</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=602716098&start_sha=dc6e662866d0e5af8db6edcd81328f3b7bb2433e)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Mar 6, 2023, 16:34

added 1 commit

<ul><li>77c7936a - Displaying extracted metadata in JSON format within a textarea &amp; implementing...</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=620624670&start_sha=c647923feb0b704ddbde387a53c3c843959514e8)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Mar 6, 2023, 16:46

added 1 commit

<ul><li>1ae64a9f - Implement downloading feature for extracted metadata in JSON format</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=620641485&start_sha=77c7936ad226e718886806edf75f4fb0f309068d)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Mar 6, 2023, 16:51

added 1 commit

<ul><li>86431b67 - Add URL pattern to enable downloading of extracted metadata</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=620647228&start_sha=1ae64a9f578f22352326ff2bc45a5296dd506f80)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Mar 25, 2023, 14:57

added 1 commit

<ul><li>a1d62b35 - Update textarea and download button (works for single key: value changes)</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=638451465&start_sha=86431b67a3c52565b95a72b907d4d5e9d629c74b)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Mar 25, 2023, 15:09

added 1 commit

<ul><li>266d67a3 - Update textarea and download button (works for single key: value changes)</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=638452897&start_sha=a1d62b352ad17b9ea2f2021ad108401158e1a63f)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Mar 25, 2023, 15:45

added 1 commit

<ul><li>0a86ebcd - Modify index function responsible of passing the initial extracted metadata</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=638457482&start_sha=266d67a34052cb77920f3a375bdcf29020ba5d11)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 4, 2023, 00:25

added 1 commit

<ul><li>5f39ca44 - Design refinement of the initial form (Added information Tool-tip and...</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=646373629&start_sha=0a86ebcd0658fe2424c75ce1e150d669f310589c)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 4, 2023, 00:39

added 1 commit

<ul><li>a184c39c - Design refinement: cleaned up html file from css &amp; js, more structured form </li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=646379749&start_sha=5f39ca44a8fc9d7e6bdd963fcb44c953e64b744b)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 4, 2023, 00:51

added 1 commit

<ul><li>8d31f349 - Refinement of style of the initial form (index.html) &amp; output form (showdata.html)</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=646384351&start_sha=a184c39c74d7fcda1ce11676589c23431eca3bbd)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 4, 2023, 11:21

added 1 commit

<ul><li>bec77ed6 - Added script responsible for editing and downloading extracted metadata as Json</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=646777507&start_sha=8d31f34998f41fea3768501b093f0bceee0350e8)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 4, 2023, 11:55

added 1 commit

<ul><li>0da7c928 - Apply change on &quot;programmingLanguages&quot;, (remove keys from...</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=646829359&start_sha=bec77ed6c100dcdbd79d977e12a5dc095d78d381)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 4, 2023, 11:58

added 1 commit

<ul><li>9c8d05c0 - custom Django template filters for checking types</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=646834209&start_sha=0da7c9288c65668588088d7b68c495c683f57dd5)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 4, 2023, 12:00

added 1 commit

<ul><li>c06e6ac6 - custom Django template filters for checking types</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=646836826&start_sha=9c8d05c0b5edf5b25d2db5aa0dc77f4b57e05d0b)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 4, 2023, 12:06

added 1 commit

<ul><li>1000ee3d - Update on comments</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=646845611&start_sha=c06e6ac6e527836086926b547578a7d1f068b55e)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 4, 2023, 21:03

**Features**
- Metadata of a GitLab project can be extracted via "Project URL" and "Personal Token Key".
- Tooltip, added to the initial form, gives more information to the user about the "Personal Token Key".
- The entered URL is displayed at the top of the form that shows the extracted metadata.
- Metadata is being shown in the format of a form including labels as keys and inputs as values.
- Data in the form can be edited.
- Extracted "Programming Languages" are displayed in a single input field, separated by commas.
- Number of "Contributors" can be calculated and shown dynamically after extraction.
- Metadata is being shown in a textarea in the JSON format.
- There is a possibility of seeing the changed data simultaneously in the textarea.
- Main JSON data or edited version can be downloaded via a download button.
- Style of the software becomes more structured.

**Needs to be solved**
- "Contributors" and "Authors" cannot be edited via the form.

**Comment by sferenz** [comment]
Hi Aida,
thanks for the merge request and the great work! I just found some small issues:
- When I try to run it, I get the following error `ModuleNotFoundError: No module named 'gitlab'` Probably, the requirements.txt need to be updated?
- In metadataExtractor.py, there are a lot of functions within the big function. It would be nicer if the function are all separated, which would make the code easier to understand.
- Can you please check the indentation and line length? In metadataExtractor, they looked a bit odd. Please use [pep8](https://pep8.org/) as an orientation here :)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 5, 2023, 22:40

added 1 commit

<ul><li>0253f685 - Update requirements.txt</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=648729846&start_sha=1000ee3db5764693347e5556c43dc2bc7ea3718a)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 6, 2023, 00:16

added 1 commit

<ul><li>b97d25b8 - Make changes to be compatible with &#39;pep8&#39;: fixed indentation, line length, some variable names</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=648781445&start_sha=0253f6856d25bec082fe5161e0c90fe85624644b)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 6, 2023, 00:36

added 1 commit

<ul><li>bc7bdb05 - Apply change on function name &#39;data_extraction&#39; compatible with &#39;PEP8&#39;</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=648791450&start_sha=b97d25b80d5ef46172a48253873759ee71ed02f2)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 6, 2023, 00:47

added 1 commit

<ul><li>ab564ac3 - Update variable names &#39;gl_url&#39;, and &#39;personal_token_key&#39; to be compatible with &#39;PEP8&#39;</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=648796745&start_sha=bc7bdb053f4fc699b0bd2021fb331c2ddedcf72e)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 6, 2023, 00:48

Hello Stephan, thank you for the comments.

Yes, that's right. 

- **python-gitlab** need to be installed by ``pip install python-gitlab``.
- **GitPython** need to be installed by ``pip install GitPython``.
-  These are added to _requirements.txt_.

- Regarding "metadataExtractor.py", I'll work on the separation of the functions to external files.
- Regarding last comment:
  - Name of the file is changed from 'metadataExtractor.py' to 'metadata_extractor.py'.
  - Problems with indentation, line length, and some variable names' has been solved.

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 9, 2023, 01:04

added 1 commit

<ul><li>65639a85 - Update metadata_extractor.py: move data filtering functions out of the main function</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=650769232&start_sha=ab564ac33bf0c956aac0ce5ef6a3934ca15b54e5)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 9, 2023, 01:08

 "metadata_extractor.py" is updated, and data filtering functions have been moved out of the main function.

**Comment by sferenz** [comment]
Thank you for the update! The requirements work now, I get the following error:
```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ferenz/projects/meta_tool/env_meta/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/ferenz/projects/meta_tool/env_meta/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/home/ferenz/projects/meta_tool/env_meta/lib/python3.10/site-packages/django/core/management/base.py", line 438, in check
    all_issues = checks.run_checks(
  File "/home/ferenz/projects/meta_tool/env_meta/lib/python3.10/site-packages/django/core/checks/registry.py", line 77, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/ferenz/projects/meta_tool/env_meta/lib/python3.10/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/ferenz/projects/meta_tool/env_meta/lib/python3.10/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/ferenz/projects/meta_tool/env_meta/lib/python3.10/site-packages/django/urls/resolvers.py", line 446, in check
    for pattern in self.url_patterns:
  File "/home/ferenz/projects/meta_tool/env_meta/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ferenz/projects/meta_tool/env_meta/lib/python3.10/site-packages/django/urls/resolvers.py", line 632, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ferenz/projects/meta_tool/env_meta/lib/python3.10/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ferenz/projects/meta_tool/env_meta/lib/python3.10/site-packages/django/urls/resolvers.py", line 625, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ferenz/projects/meta_tool/meta_tool/urls.py", line 27, in <module>
    include('meta_creator.urls', namespace='meta_creator')
  File "/home/ferenz/projects/meta_tool/env_meta/lib/python3.10/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ferenz/projects/meta_tool/meta_creator/urls.py", line 10, in <module>
    urlpatterns = [path("", views.IndexView.as_view(), name="index"), path('download_json/', views.download_json, name='download_json')] + [re_path(r'^admin/', admin.site.urls)] + [re_path(r'^getdata/', views.index , name="getdata")] + [re_path(r'^$', views.index)] + [path(versions, views.CreatorView.as_view(metapath=metapath)) for versions, metapath in META_VERSIONS.items()]
AttributeError: module 'meta_creator.views' has no attribute 'download_json'
```

Do you reproduce that behaviour or have an idea what I need to change on my system?

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 11, 2023, 14:40

- I guess this error is related to 'download_json' function in meta_creator/views.py, which is not being used in the running version of tool. 
- Would you please remove the commented lines of the function **'download_json'** in meta_creator/views.py on your machine. 
- Also in meta_creator/urls.py, please remove the following commented lines: \
`#path('download_json/', views.download_json, name='download_json'),` \
`#path('showdata/', views.showdata, name='showdata'),`\
`#re_path(r'^update_metadata/', views.update_metadata, name="update_metadata"),`\
`#re_path(r'^$', views.update_metadata),`\
`#path(versions, views.CreatorView.as_view(metapath=metapath)) for versions, metapath in META_VERSIONS.items(),` 
- Please let me know if the error still exists.

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 11, 2023, 15:02

added 1 commit

<ul><li>6f81ffb8 - Update urls.py</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=652401606&start_sha=65639a85e6ee3996a528a296544b220ffd3c9042)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 11, 2023, 15:09

I updated urls.py, by using \
`urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    re_path(r'^getdata/', views.index, name="getdata"),
]`
it should work.

**Comment by sferenz** [comment]
Thanks for the update, now I get the page to enter a link and a token. When I press on extract, I see the following error:
```
NameError at /meta_creator/getdata/

name 'json' is not defined
```

Can you please check that?

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 13, 2023, 00:07

added 1 commit

<ul><li>b9614282 - Add missing import</li></ul>

[Compare with previous version](/zdin-zle/zle-platform/repository/meta_tool/-/merge_requests/4/diffs?diff_id=654100464&start_sha=6f81ffb81bd36c2b0288da2ae44636c9478618fe)

**Comment by sferenz** [comment]
In GitLab by @Aidajafarbigloo on Apr 13, 2023, 00:09

Please add `import json` on top of meta_creaotr/views.py. And let me know if you face any errors.

**Comment by sferenz** [comment]
Thanks, that solves the issue!

**Comment by sferenz** [comment]
mentioned in commit 3ab59c08185589bd423a7d1425646ced0404ac1f
